import type { Metadata } from "next";
import { Saira, Tourney } from "next/font/google";
import "./globals.css";
import Footer from "./layout/footer/footer";
import Navbar from "./layout/navigation/navbar";

const saira = Saira({
    subsets: ["latin"],
    variable: "--font-saira",
});
const tourney = Tourney({ subsets: ["latin"], variable: "--font-tourney" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${saira.variable} ${tourney.variable}`}>
                <Navbar />
                {children}
            </body>
            <Footer />
        </html>
    );
}
